name: Run validations on all repositories

on:
  schedule:
    - cron: "0 0 * * 0" # every week on Sunday at midnight
  workflow_dispatch: # allows manual triggering from the GitHub UI
    inputs:
      branch:
        description: "Branch of the repository" # e.g., develop
        default: develop
        type: string
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      branch:
        description: "Branch of the repository" # e.g., develop
        default: ${{ github.ref_name }}
        type: string

jobs:
  countryconfig:
    uses: ./.github/workflows/validate-github-repo-with-graphql-schema.yml
    with:
      repository: opencrvs/opencrvs-countryconfig
      branch: ${{ inputs.branch }}
      schema: https://raw.githubusercontent.com/opencrvs/opencrvs-core/refs/heads/${{ inputs.branch }}/packages/gateway/src/graphql/schema.graphql
  farajaland:
    uses: ./.github/workflows/validate-github-repo-with-graphql-schema.yml
    with:
      repository: opencrvs/opencrvs-farajaland
      branch: ${{ inputs.branch }}
      schema: https://raw.githubusercontent.com/opencrvs/opencrvs-core/refs/heads/${{ inputs.branch }}/packages/gateway/src/graphql/schema.graphql
  dci-crvs-api:
    uses: ./.github/workflows/validate-github-repo-with-graphql-schema.yml
    with:
      repository: opencrvs/dci-crvs-api
      branch: ${{ inputs.branch }}
      schema: https://raw.githubusercontent.com/opencrvs/opencrvs-core/refs/heads/${{ inputs.branch }}/packages/gateway/src/graphql/schema.graphql
